# Generated by Django 6.0.6 on 2026-06-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_music_data_alter_music_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_data',
            field=models.FileField(blank=True, null=True, upload_to='musics/'),
        ),
    ]
