# Generated by Django 6.0.6 on 2026-06-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_music_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_data',
            field=models.FileField(default=1, upload_to='musics/'),
            preserve_default=False,
        ),
    ]
