# Generated by Django 6.0.6 on 2026-06-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_music_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='favourites_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='saves_count',
            field=models.IntegerField(default=0),
        ),
    ]
